defaults: &defaults
  working_directory: ~/buildbox
  docker:
    - image: cimg/ruby:3.1.2
      environment:
        DATABASE_HOST: localhost
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_DEVELOPMENT: data_development
        DATABASE_TEST: data_test
    - image: cimg/redis:7.0.0
    - image: cimg/postgres:14.0
      environment:
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres

databases: &databases
  docker:
    - image: cimg/redis:7.0.0
    - image: cimg/postgres:14.0
      environment:
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres

version: 2.0
jobs:
  test:
    <<: *defaults
    <<: *databases
    steps:
      - checkout
      - run:
          name: Install libvips42, graphviz, postgresql-client & nodejs 16.x
          command: |
            sudo sudo apt update && sudo apt install -y libvips42 graphviz postgresql-client || true
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt install -y nodejs

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-cache-{{ checksum "Gemfile.lock" }}
            - rails-cache-

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      # Store bundle cache
      - save_cache:
          key: rails-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate

      - run:
          name: Parallel RSpec
          command: bundle exec rspec

      # Save artifacts
      - store_test_results:
          path: /tmp/rspec-results

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14

      - run:
          name: Login to Docker registry
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build image
          command: docker build --build-arg ARG_RAILS_MASTER_KEY=$ARG_RAILS_MASTER_KEY -t tanngoc93/king_sumo_clone:latest .

      - run:
          name: Push image to Docker registry
          command: docker push tanngoc93/king_sumo_clone:latest

  deploy:
    machine:
       enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ac:37:08:41:f7:3e:dd:30:ac:b0:69:9a:e1:4f:1d:28"

      - run:
          name: Deploy Over SSH
          command: |
            ssh root@206.189.95.189 "cd wordpress-docker && docker-compose pull rails && docker-compose up -d"

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main